### ISSUE TITLE
istio-pilot cannot get gateway ip when deployed with Charmed Kubeflow on AWS

### ISSUE THREAD

**Issue by hychiu** [canonical/istio-operators#117]
**Environment**

Bundle - Charmed kubeflow 1.6/beta
Platform - OpenShift, 4.9.0-0.okd-2022-02-12-140851
Cloud provider - AWS

**Description**

My `istio-pilot` pod's shows:

```
2022-09-06 08:42:35 INFO juju.worker.uniter.operation runhook.go:146 ran "ingress-relation-changed" hook (via hook dispatching script: dispatch)
2022-09-06 08:42:38 INFO juju-log ingress-auth:10: No gateway address returned - this may be transitory, but if it persists it is likely an unexpected error. Deferring this event 
```

And I found [this line](https://github.com/canonical/istio-operators/blob/main/charms/istio-pilot/src/charm.py#L329) try to get the `ip` field that does not exist on AWS. 

```
$ kubectl get svc istio-ingressgateway-workload -n kubeflow -o yaml
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2022-09-06T08:42:34Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: istio-ingressgateway
    app.juju.is/created-by: istio-ingressgateway
    install.operator.istio.io/owning-resource: unknown
    istio: ingressgateway
    istio.io/rev: default
    operator.istio.io/component: IngressGateways
    release: istio
  name: istio-ingressgateway-workload
  namespace: kubeflow
  resourceVersion: "1039086"
  uid: ae2b8c45-94c2-4900-99b5-162efcc7243e
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 172.30.134.191
  clusterIPs:
  - 172.30.134.191
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http2
    nodePort: 32693
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: https
    nodePort: 30489
    port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    istio: ingressgateway
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - hostname: xxxxxxxxxxxxxxxxxx.us-east-1.elb.amazonaws.com
``` 

```
$ kubectl explain service.status.loadBalancer.ingress
...
FIELDS:
   hostname	<string>
     Hostname is set for load-balancer ingress points that are DNS based
     (typically AWS load-balancers)

   ip	<string>
     IP is set for load-balancer ingress points that are IP based (typically GCE
     or OpenStack load-balancers)
...
```

What should I do to fix this?

**Comment by ca-scribner** [comment]
Hi @hychiu, sorry for the slow response.  

I see what you're pointing out.  I thought this was tested and working in AWS like you're running, but maybe we missed it.  Without having dug further, the part of the code you point out doesn't look like it could work in your setup (where the `ingress[0].hostname` is defined, rather than `ingress[0].ip`.  

The only quick fix I can think of is:
* fork the charm
* modify the `charm.py` file where you points to, maybe adding a try/except or if `ip` doesn't exist, try `hostname`
* in the `charms/istio-pilot` directory, `charmcraft pack` the charm
* deploy your version: `juju deploy ./path-to-locally-built-charm.py`

For a real fix, I think we've got to research a bit and then probably do the same steps as above.

If you do give this a try, please let us know how it goes.  Thanks!

**Comment by i-chvets** [comment]
Dev is completed. Need to test on EKS. Could not create EKS cluster in AWS us-east. Managed to create EKS cluster in AWS us-west, but EKS could not schedule the workload.

**Comment by i-chvets** [comment]
Closing.
