### ISSUE TITLE
bundle tests do not correctly wait_for_idle during deployment

### ISSUE THREAD

**Issue by ca-scribner** [canonical/istio-operators#303]
https://github.com/canonical/istio-operators/blob/6c1e58db3626d8cccf4c809e128f8a9f7446f6c7/tests/test_bundle.py#L107 introduces a race condition where `wait_for_idle` does not actually wait for the charms to go idle, leading to flaky tests.  As a workaround, we use a long retry on tenacity checks to ensure things are up

**Comment by ca-scribner** [comment]
This may be resolved by https://github.com/juju/python-libjuju/issues/900

**Comment by orfeas-k** [comment]
This should be fixed by using python lib juju `2.9.44` or greater. Except from checking that this stands, we should also send a PR removing the workaround as well ([function](https://github.com/canonical/istio-operators/blob/6c1e58db3626d8cccf4c809e128f8a9f7446f6c7/tests/test_bundle.py#L389-L408) and [calls like this](https://github.com/canonical/istio-operators/blob/6c1e58db3626d8cccf4c809e128f8a9f7446f6c7/tests/test_bundle.py#L117)).
