### ISSUE TITLE
Research the `AuthorizationPolicies` created by upstream Kubeflow

### ISSUE THREAD

**Issue by ca-scribner** [canonical/istio-operators#362]
### Context

To support improved [network isolation of Charmed Kubeflow components](https://warthogs.atlassian.net/browse/KF-4800), we need to document all the `AuthorizationPolicy` objects that are created by upstream Kubeflow.  These could be created via upstream controllers or manifests.

### What needs to get done

Review the upstream kubeflow manifests and sample deployments of Kubeflow to identify all `AuthorizationPolicies` that exist.  For simple cases (say an `AuthorizationPolicy` created in a kubeflow manifest for the core Kubeflow experience), document them directly.  For more complex cases (say the policies created by kfp or the profile controllers), create follow-on tasks to investigate these further.  

### Definition of Done

1. For all `AuthorizationPolicies` which can be investigated quickly, a spec or issue has been created that documents them
2. For all `AuthorizationPolicies` that need additional research (for example, the `AuthorizationPolicies` created by the profile controller) a new task has been created that includes them

**Comment by ca-scribner** [comment]
Included in scope here is the `global-deny-all` policy from upstream - that should be documented when completing this issue.

**Comment by ca-scribner** [comment]
It might not really be in-scope for this issue, but noting here that if we apply a `deny-all` policy then the ingress created by `istio-pilot` will also have its traffic controlled, as mentioned [here](https://github.com/istio/istio/issues/35626).  We'd need to add an `AuthorizationPolicy` similar to the linked issue's `allow-ingress-to-apps` for our ingresses

**Comment by ca-scribner** [comment]
This should also take note of how upstream is targeting these policies - lots of the upstream policies match on labels, service accounts, etc.

**Comment by ca-scribner** [comment]
We should also take note of any `AuthorizationPolicies` that need to be created individually for each user, as they'll need to be implemented through something like the [resource dispatcher](https://github.com/canonical/resource-dispatcher)

**Comment by DnPlas** [comment]
#### From manifest files 

The following information has been extracted from the manifests generated by cloning the kubeflow/kubeflow (checkout to 1.8 branch) repository and running `while ! kustomize build example | tee kubeflow-1.8.yaml`

*   Istio
```
name: cluster-local-gateway
namespace: istio-system
---
name: global-deny-all
namespace: istio-system
---
name: istio-ingressgateway
namespace: istio-system
```

* KNative

```
name: activator-service
namespace: knative-serving
---
name: autoscaler
namespace: knative-serving
---
name: controller
namespace: knative-serving
---
name: istio-webhook
namespace: knative-serving
---
name: webhook
namespace: knative-serving
```

* Dashboard
```
name: central-dashboard
namespace: kubeflow
```

* Jupyter
```
name: jupyter-web-app
namespace: kubeflow
```

* Katib
```
name: katib-ui
namespace: kubeflow
```

* Kserve

```
name: kserve-models-web-app
namespace: kubeflow
```
* Metadata GRPC Service (mlmd)

```
name: metadata-grpc-service
namespace: kubeflow
```
* Minio

```
name: minio-service
namespace: kubeflow
```

* Pipelines
```
name: ml-pipeline
namespace: kubeflow
---
name: ml-pipeline-ui
namespace: kubeflow
---
name: ml-pipeline-visualizationserver
namespace: kubeflow
```

* MySQL

```
name: mysql
namespace: kubeflow
```

* Kubeflow profile controller
```
name: profiles-kfam
namespace: kubeflow
```

* Cache server
```
name: service-cache-server
namespace: kubeflow
```

* Tensorboards web app

```
name: tensorboards-web-app
namespace: kubeflow
```
* Kubeflow volumes web app

```
name: volumes-web-app
namespace: kubeflow
```

#### From deploying Kubeflow from upstream

The following information has been extracted from the deployment of Kubeflow using `while ! kustomize build example | kubectl apply -f -; do echo "Retrying to apply resources"; sleep 10; done`

```
NAMESPACE                   NAME                              AGE
istio-system                cluster-local-gateway             13m
istio-system                global-deny-all                   13m
istio-system                istio-ingressgateway              13m
knative-serving             activator-service                 13m
knative-serving             autoscaler                        13m
knative-serving             controller                        13m
knative-serving             istio-webhook                     13m
knative-serving             webhook                           13m
kubeflow-user-example-com   ns-owner-access-istio             7m46s
kubeflow                    central-dashboard                 13m
kubeflow                    jupyter-web-app                   13m
kubeflow                    katib-ui                          13m
kubeflow                    kserve-models-web-app             13m
kubeflow                    metadata-grpc-service             13m
kubeflow                    minio-service                     13m
kubeflow                    ml-pipeline                       13m
kubeflow                    ml-pipeline-ui                    13m
kubeflow                    ml-pipeline-visualizationserver   13m
kubeflow                    mysql                             13m
kubeflow                    profiles-kfam                     13m
kubeflow                    service-cache-server              13m
kubeflow                    tensorboards-web-app              13m
kubeflow                    volumes-web-app                   13m
```

#### Comparisons

The `AuthorizationPolicies` on both sides look exactly the same, except for the `ns-owner-access-istio` AP present in the deployment. This is because the `kubeflow-profiles` controller creates an AP for that profile in particular.

#### Extra AuthorizationPolicies

The `kubeflow-pipelines-profile-controller` has an `AuthorizationPolicy` that gets created for Kubeflow in multi-user mode for each user (profile) that gets created. The code that actually applies this AP can be found [here](https://github.com/kubeflow/pipelines/blob/master/manifests/kustomize/base/installs/multi-user/pipelines-profile-controller/sync.py#L226C1-L246C19).

**Comment by ca-scribner** [comment]
When we get to implementing these, we need to be aware of the workload selectors for these AuthorizationPolicies, especially for those created by anything upstream (at least for kubeflow profiles, maybe also kfp via sync.py).  The `WorkloadSelector` for these points at labels that we may not have in our deployment (example: the visualization server for kfp is deployed as a sidecar so its pod doesn't have upstream's labels)
